---
- name: Prepare compute node
  hosts:
    - compute
  tasks:
    - name: Update repo
      ansible.builtin.command: sudo apt update
    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - chrony
        state: present

    - name: Copy hosts file
      ansible.builtin.template:
        src: openstack/chrony.conf
        dest: /etc/chrony
        owner: root
        group: root
        mode: "0644"
        backup: false
    - name: Restart chorny
      ansible.builtin.command: systemctl restart chronyd
- name: Prepare controller node
  hosts:
    - controller
  tasks:
    - name: Update repo
      ansible.builtin.command: sudo apt update
    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - chrony
        state: present

    - name: Copy hosts file
      ansible.builtin.template:
        src: openstack/chrony.conf
        dest: /etc/chrony
        owner: root
        group: root
        mode: "0644"
        backup: false
    - name: Restart chorny
      ansible.builtin.command: systemctl restart chronyd
- name: Build deployment nodes
  hosts:
    - kola
  vars:
    - kola_dir: /etc/kolla/
  tasks:
    - name: Update repo
      ansible.builtin.command: sudo apt update
    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - git
          - python3-dev
          - libffi-dev
          - gcc
          - libssl-dev
          - python3-pip
          - sshpass
          - jq
          - chrony
        state: present

    - name: Restart chorny
      ansible.builtin.command: systemctl restart chronyd
    - name: Upgrade pip to latest version
      ansible.builtin.command: sudo pip3 install -U pip
    - name: Install ansible
      ansible.builtin.pip:
        name:
          - git+https://opendev.org/openstack/kolla-ansible@stable/2023.1
          - ansible>=6,<8
          - ansible-core>=2.13,<=2.14.2
          - python-openstackclient
          - python-magnumclient
          - python-barbicanclient
          - pip install diskimage-builder

    - name: Clean
      ansible.builtin.command: rm -rf /etc/kolla/
    - name: Create the /etc/kolla directory
      ansible.builtin.file:
        path: "{{ kola_dir }}"
        state: directory
        recurse: true
        owner: root
        group: root

    - name: Create the customize config kolla directory
      ansible.builtin.file:
        path: "{{ kola_dir }}/config"
        state: directory
        recurse: true
        owner: root
        group: root

    - name: Copy customize config to the kolla config directory
      ansible.builtin.copy:
        src: openstack/config/
        dest: "{{ kola_dir }}/config"

    - name: Copy hosts file
      ansible.builtin.template:
        src: openstack/chrony.conf
        dest: /etc/chrony
        owner: root
        group: root
        mode: "0644"
        backup: false

    - name: Copy globals.yml and passwords.yml to /etc/kolla directory
      ansible.builtin.shell: cp -r /usr/local/share/kolla-ansible/etc_examples/kolla/* /etc/kolla

    - name: Copy all-in-one and multinode inventory files to the current directory
      ansible.builtin.shell: cp /usr/local/share/kolla-ansible/ansible/inventory/* /etc/kolla

    - name: Passwords used in our deployment are stored in /etc/kolla/passwords.yml
      ansible.builtin.command: kolla-genpwd
    - name: Deploy hosts file
      ansible.builtin.template:
        src: openstack/hosts
        dest: /etc/
        owner: root
        group: root
        mode: "0644"
        backup: false

    - name: Deploy globals template
      ansible.builtin.template:
        src: openstack/config/globals.yml
        dest: "{{ kola_dir }}"
        owner: root
        group: root
        mode: "0644"
        backup: false

    - name: Deploy multinode template
      ansible.builtin.template:
        src: openstack/multinode
        dest: "{{ kola_dir }}"
        owner: root
        group: root
        mode: "0644"
        backup: false

    - name: Deploy globals template
      ansible.builtin.template:
        src: openstack/ansible.cfg
        dest: "{{ kola_dir }}"
        owner: root
        group: root
        mode: "0644"
        backup: false

    - name: Install-deps
      ansible.builtin.command: kolla-ansible install-deps
    - name: Generate octavia-certificate
      ansible.builtin.command: kolla-ansible octavia-certificates
